format_version: v1.0
configName: lvdsc_xlcdc_rgba8888_mxt_9x75_wvga
folderName: legato_wm_9x75_eb_ac69t88a
frameworkPath: c:\harmony3_latest
processor: SAM9X75
projectName: legato_wm_9x75_eb_ac69t88a
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAM9X7_DFP\0.0.19\atdf\SAM9X75.atdf
