configName: lvdsc_xlcdc_rgba8888_mxt_9x75_wvga
folderName: legato_qs_9x75_eb_ac69t88a
format_version: v1.0
frameworkPath: C:\Harmony3
processor: SAM9X75
projectName: legato_qs_9x75_eb_ac69t88a
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAM9X7_DFP\1.1.120
